.PHONY: clean All

All:
	@echo "----------Building project:[ a_star - Debug ]----------"
	@"$(MAKE)" -f  "a_star.mk"
clean:
	@echo "----------Cleaning project:[ a_star - Debug ]----------"
	@"$(MAKE)" -f  "a_star.mk" clean
